In [123]:
b = [[True]*3]*2
b

[[True, True, True], [True, True, True]]

In [124]:
b[0]

[True, True, True]

In [125]:
b[0][1] = False

In [126]:
b

[[True, False, True], [True, False, True]]

In [127]:
import numpy as np

In [128]:
b = [[True]*3]*2

In [129]:
ba = np.array(b)

In [130]:
ba[1,2] = False

In [131]:
ba

array([[ True,  True,  True],
       [ True,  True, False]])

In [132]:

# TODO: implement the __init__ class below by adding properties
# that meet the three requirements specified
import numpy as np

WIDTH = 3
HEIGHT = 2

class GameState:

    def __init__(self):
        """The GameState class constructor performs required
        initializations when an instance is created. The class
        should:
        
        1) Keep track of which cells are open/closed
        2) Identify which player has initiative
        3) Record the current location of each player
        
        Parameters
        ----------
        self:
            instance methods automatically take "self" as an
            argument in python
        
        Returns
        -------
        None
        """
        # You can define attributes like this:
        # self.value = 73  # an arbitrary number
        # reassign it to a string (variable type is dynamic in Python)
        # self.value = "some string"
        # self.foo = []  # create an empty list
        self.open_cells = np.array([[True]*WIDTH]*HEIGHT)
        self.open_cells[1, 2] = False
        self.current_player = 0
        self.player_locations = [None, None]

In [133]:
game = GameState()

In [134]:
game.open_cells

array([[ True,  True,  True],
       [ True,  True, False]])

## Fill some methods of GameState

In [135]:
import numpy as np
import copy

WIDTH = 3
HEIGHT = 2

class GameState:

    def __init__(self):
        self.open_cells = np.array([[True]*WIDTH]*HEIGHT)
        self.open_cells[HEIGHT - 1, WIDTH - 1] = False
        self.current_player = 0
        self.player_locations = [None, None]
        
    def actions(self):
        """ Return a list of legal actions for the active player 
        
        You are free to choose any convention to represent actions,
        but one option is to represent actions by the (row, column)
        of the endpoint for the token. For example, if your token is
        in (0, 0), and your opponent is in (1, 0) then the legal
        actions could be encoded as (0, 1) and (0, 2).
        """
        return [(x, y) for x in range(HEIGHT) for y in range(WIDTH) 
                if self.open_cells[x,y]]
    
    def player(self):
        """ Return the id of the active player 
        
        Hint: return 0 for the first player, and 1 for the second player
        """
        return self.current_player
    
    def result(self, action):
        """ Return a new state that results from applying the given
        action in the current state
        
        Hint: Check out the deepcopy module--do NOT modify the
        objects internal state in place
        """
        assert action in self.actions()  # Check if the action is valid
        new_state = copy.deepcopy(self)
        new_state.open_cells[action] = False
        new_state.player_locations[self.player()] = action
        new_state.current_player = 0 if self.player() == 1 else 1
        return new_state
    
    def terminal_test(self):
        """ return True if the current state is terminal,
        and False otherwise
        
        Hint: an Isolation state is terminal if _either_
        player has no remaining liberties (even if the
        player is not active in the current state)
        """
        # TODO: Finish this function!
        pass
    
    def liberties(self, loc):
        """ Return a list of all open cells in the
        neighborhood of the specified location.  The list 
        should include all open spaces in a straight line
        along any row, column or diagonal from the current
        position. (Tokens CANNOT move through obstacles
        or blocked squares in queens Isolation.)
        
        Note: if loc is None, then return all empty cells
        on the board
        """
        if loc is None:
            return self.actions()
        return None

In [136]:
game = GameState()

In [137]:
game.actions()

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1)]

In [138]:
game.open_cells[(1,2)]

False

In [139]:
player = 0

In [140]:
player = 0 if player == 1 else 1
player

1

In [141]:
game.open_cells

array([[ True,  True,  True],
       [ True,  True, False]])

In [142]:
HEIGHT = 8
WIDTH = 8
game = GameState()

In [143]:
game.open_cells

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False]])

In [144]:
def horiz_next(loc):
    if loc[1] + 1 < WIDTH:
        return (loc[0], loc[1] + 1)
    else:
        return None

def horiz_prev(loc):
    if loc[1] - 1 >= 0:
        return (loc[0], loc[1] - 1)
    else:
        return None

def vert_next(loc):
    if loc[0] + 1 < HEIGHT:
        return (loc[0] + 1, loc[1])
    else:
        return None

def vert_prev(loc):
    if loc[0] - 1 >= 0:
        return (loc[0] - 1, loc[1])
    else:
        return None

def diag1_next(loc):
    if (loc[0] + 1 < WIDTH) and (loc[1] + 1 < HEIGHT):
        return (loc[0] + 1, loc[1] + 1)
    else:
        return None

def diag1_prev(loc):
    if (loc[0] - 1 >= 0) and (loc[1] - 1 >= 0):
        return (loc[0] - 1, loc[1] - 1)
    else:
        return None

def diag2_next(loc):
    if (loc[0] + 1 < WIDTH) and (loc[1] - 1 >= 0):
        return (loc[0] + 1, loc[1] - 1)
    else:
        return None

def diag2_prev(loc):
    if (loc[0] - 1 >= 0) and (loc[1] + 1 < HEIGHT):
        return (loc[0] - 1, loc[1] + 1)
    else:
        return None

In [145]:
game.open_cells

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False]])

In [146]:
def show_points(points):
    board = np.zeros((HEIGHT, WIDTH))
    for p in points:
        board[p] = 1
    print(board)

In [147]:
u = np.zeros((HEIGHT, WIDTH))
l = [(1,2), (1,3), (1,4)]
for p in l:
    u[p] = 1
u

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [148]:
show_points(l)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [149]:
loc = (3, 3)
show_points([loc])

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [150]:
current = loc
path = list()
while current is not None:
    current = horiz_next(current)
    path.append(current)
path = path[:-1]
show_points(path)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [151]:
current = loc
path = list()
while current is not None:
    current = horiz_prev(current)
    path.append(current)
path = path[:-1]
show_points(path)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [152]:
current = loc
path = list()
while current is not None:
    current = vert_next(current)
    path.append(current)
path = path[:-1]
show_points(path)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


In [153]:
current = loc
path = list()
while current is not None:
    current = vert_prev(current)
    path.append(current)
path = path[:-1]
show_points(path)

[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [154]:
current = loc
path = list()
while current is not None:
    current = diag1_next(current)
    path.append(current)
path = path[:-1]
show_points(path)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [155]:
current = loc
path = list()
while current is not None:
    current = diag1_prev(current)
    path.append(current)
path = path[:-1]
show_points(path)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [156]:
current = loc
path = list()
while current is not None:
    current = diag2_next(current)
    path.append(current)
path = path[:-1]
show_points(path)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [157]:
current = loc
path = list()
while current is not None:
    current = diag2_prev(current)
    path.append(current)
path = path[:-1]
show_points(path)

[[0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [158]:
move_funcs = [
    horiz_next,
    horiz_prev,
    vert_next,
    vert_prev,
    diag1_next,
    diag1_prev,
    diag2_next,
    diag2_prev
]

In [159]:
def liberties_in_dir(loc, move_fun, board):
    current = loc
    path = list()
    while (current is not None) and board[current]:
        current = move_fun(current)
        path.append(current)
    return path[:-1]

In [160]:
h_liberties = liberties_in_dir((1,2), horiz_next, game.open_cells)
show_points(h_liberties)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [161]:
liberties = [liberties_in_dir((1,2), move_fun, game.open_cells) for move_fun in move_funcs]
print(liberties)

[[(1, 3), (1, 4), (1, 5), (1, 6), (1, 7)], [(1, 1), (1, 0)], [(2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2)], [(0, 2)], [(2, 3), (3, 4), (4, 5), (5, 6), (6, 7)], [(0, 1)], [(2, 1), (3, 0)], [(0, 3)]]


In [162]:
import itertools

In [163]:
list(itertools.chain(*liberties))

[(1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 1),
 (1, 0),
 (2, 2),
 (3, 2),
 (4, 2),
 (5, 2),
 (6, 2),
 (7, 2),
 (0, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (0, 1),
 (2, 1),
 (3, 0),
 (0, 3)]

In [164]:
show_points(itertools.chain(*liberties))

[[0. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


In [171]:
import numpy as np
import copy

WIDTH = 3
HEIGHT = 2
move_funcs = [
    horiz_next,
    horiz_prev,
    vert_next,
    vert_prev,
    diag1_next,
    diag1_prev,
    diag2_next,
    diag2_prev
]


def liberties_in_dir(loc, move_fun, board):
    current = loc
    path = list()
    while (current is not None) and board[current]:
        current = move_fun(current)
        path.append(current)
    return path[:-1]


class GameState:

    def __init__(self):
        self.open_cells = np.array([[True]*WIDTH]*HEIGHT)
        self.open_cells[HEIGHT - 1, WIDTH - 1] = False
        self.current_player = 0
        self.player_locations = [None, None]
        
    def actions(self):
        """ Return a list of legal actions for the active player 
        
        You are free to choose any convention to represent actions,
        but one option is to represent actions by the (row, column)
        of the endpoint for the token. For example, if your token is
        in (0, 0), and your opponent is in (1, 0) then the legal
        actions could be encoded as (0, 1) and (0, 2).
        """
        return [(x, y) for x in range(HEIGHT) for y in range(WIDTH) 
                if self.open_cells[x,y]]
    
    def player(self):
        """ Return the id of the active player 
        
        Hint: return 0 for the first player, and 1 for the second player
        """
        return self.current_player
    
    def result(self, action):
        """ Return a new state that results from applying the given
        action in the current state
        
        Hint: Check out the deepcopy module--do NOT modify the
        objects internal state in place
        """
        assert action in self.actions()  # Check if the action is valid
        new_state = copy.deepcopy(self)
        new_state.open_cells[action] = False
        new_state.player_locations[self.player()] = action
        new_state.current_player = 0 if self.player() == 1 else 1
        return new_state
    
    def terminal_test(self):
        """ return True if the current state is terminal,
        and False otherwise
        
        Hint: an Isolation state is terminal if _either_
        player has no remaining liberties (even if the
        player is not active in the current state)
        """
        terminal = len(self.liberties(self.player_locations[0])) == 0
        terminal = terminal or len(self.liberties(self.player_locations[1])) == 0
        return terminal
    
    def liberties(self, loc):
        """ Return a list of all open cells in the
        neighborhood of the specified location.  The list 
        should include all open spaces in a straight line
        along any row, column or diagonal from the current
        position. (Tokens CANNOT move through obstacles
        or blocked squares in queens Isolation.)
        
        Note: if loc is None, then return all empty cells
        on the board
        """
        if loc is None:
            return self.actions()
        liberties = [liberties_in_dir(loc, move_fun, self.open_cells) 
                     for move_fun in move_funcs]
        return list(itertools.chain(*liberties))

In [172]:
game = GameState()

In [173]:
game.open_cells

array([[ True,  True,  True],
       [ True,  True, False]])

In [174]:
game.liberties((0,1))

[(0, 2), (0, 0), (1, 1), (1, 0)]

In [175]:
def show_points(points):
    board = np.zeros((HEIGHT, WIDTH))
    for p in points:
        board[p] = 1
    print(board)

In [176]:
show_points(game.liberties((0,1)))

[[1. 0. 1.]
 [1. 1. 0.]]
